print ("lll                                xxxx                      xxxx")
print ("lll                                 xxxx                   xxxx")
print ("lll                                   xxxx               xxxx")
print ("lll                                     xxxx           xxxx")
print ("lll                                       xxxx       xxxx")
print ("lll                                          xxxx   xxxx")
print ("lll                                          xxxxxxxx"  )
print ("lll                                            xxxx")
print ("lll                                          xxxxxxxx")
print ("lll                                        xxxx    xxxx")
print ("lll                                       xxxx        xxxx")
print ("lll                                    xxxx            xxxx")
print ("lll                                  xxxx                xxxx")
print ("lllllllllllllllllll                xxxx                    xxxx")
print ("lllllllllllllllllll              xxxx                        xxxx")
